export const FETCH_EXCHANGE_REQUESTED = 'exchange/FETCH_EXCHANGE_REQUESTED';

export const EXCHANGE_FETCHING = 'exchange/FETCHING';
export const EXCHANGE_SUCCESS = 'exchange/SUCCESS';

export const TRANSACTION_COMPLETE = 'exchange/TRANSACTION_COMPLETE';
