export const AN_IDENTITY_UNCOVERED = 657;
export const CRYPTIC_CLUE = 389;
export const PRIMORDIAL_SHRIEK = 388;
export const TOUCHING_LOVE_STORY = 945;

export const SELL_PRICES = {
  [AN_IDENTITY_UNCOVERED]: 250,
  [CRYPTIC_CLUE]: 2,
  [PRIMORDIAL_SHRIEK]: 2,
  [TOUCHING_LOVE_STORY]: 250,
};
